# -*- coding: utf-8 -*-
"""
Filename: eNotes01ECT.py
Created on Fri Feb  9 20:41:48 2024

@author: Celso Co
"""

from ccoLib.ccoPlot  import *
from ccoLib.ccoLatex import *  #This is the library for Python-Tex coding.
from Data.variables import *

title="eNotes: The Conic Section"
authors="CBCO"
date=""

Preamble="\\documentclass[10pt,a4paper,leqno]{article}\n\
\\usepackage{CJKutf8}\n\
\\usepackage[utf8]{inputenc}\n\
\\usepackage[T1]{fontenc}\n\
\\usepackage{amsmath,esint}\n\
\\usepackage{amsfonts}\n\
\\usepackage{amssymb}\n\
\\usepackage{xcolor}\n\
\\usepackage{mathrsfs}\n\
\\usepackage{makeidx}\n\
\\usepackage{graphicx}\n\
\\usepackage{float}\n\
\\usepackage{gensymb}\n\
\\usepackage{textcomp}\n\
\\usepackage{longtable}\n\
\\usepackage{ifpdf}\n\
\\usepackage{tikz}                            \n\
\\usetikzlibrary{shapes,arrows}               \n\
%\\usepackage{tgothic}\n\
\\ifpdf\n\
\\usepackage[breaklinks,hidelinks]{hyperref}\n\
\\else \n\
\\usepackage{url}\n\
\\fi\n\
\\newcommand*\VF[1]{\mathbf{#1}}\n\
\\newcommand*\dif{\mathop{}\!\mathrm{d}}\n\
\\author{"+authors+"}\n\
\\title{"+title+"}\n\
\\date{"+date+"}\n\
\\begin{document}\n\
\\maketitle\n\n"


PyArt=PyArticle(Headers=Preamble)
          
             
#Shortcut Handlers 

At=PyArt.Append_Text            #Append text variable
Ae=PyArt.Append_Expression      #Append expression
Ce=PyArt.Append_Equation        #Create equation
Pb=PyArt.Build                  #Build Latex File
Af=PyArt.Append_Figure          #Append figure
Ad=PyArt.Append_Var_Dictionary  #Append Variable Dictionary
Ml=PyArt.Math_Latex             #Convertion to Math format latex    
eQ=PyArt.eQ                     #Equation List
vD=PyArt.vD                     #Variable List
   


#Multiple Choices
"""
At("\\newcommand\\CWht[1][2.5]{\\tikz[baseline=-#1]{\\draw[thick](0,0) \
    circle[radius=1.5mm];}}")
#CBlk is circle with black fill
At("\\newcommand\\CBlk[1][2.5]{\\tikz[baseline=-#1]{\\draw[thick,\
    fill=black!](0,0) circle[radius=1.5mm];}}")
"""

#Numbering equation within section
At("\\numberwithin{equation}{section} % This line resets equation numbering \
when starting a new section. \n\
\\renewcommand{\\theequation}{\\thesection.\\arabic{equation}}  \n\
%\\renewcommand{\\theequation}{Eq. \\thesection.\\arabic{equation}} % This line ads Eq.")

At("\\numberwithin{figure}{section}\n\
% \\renewcommand{\theequation}{Eq. \thesection.\arabic{equation}}")   

At("\\begin{CJK*}{UTF8}{gbsn}")

from cone01 import *

At("\\section{Introduction 介绍}")

At("A conic section is an intersection of a cone with a plnae.")
At("圆锥曲线是圆锥体与平面的交线。")


At("In Figure 1.1, the cones were plotted with two different methods.")

At("在图 1.1 中，锥体是用两种不同的方法绘制的。")


Af("Data/fgr01.png",caption="(a) Cone = f(x,y,z) plot (b) Cone = f(rho,phi,z) ",
   height=.25)

At("Open Cone01.py. Study the codes and run the file.")

At("打开 Cone01.py。 研究代码并运行文件。")

At("The equation of cone can be found at \\url{https://mathworld.wolfram.com/Cone.html} ")
At("圆锥方程可以在 \\url{https://mathworld.wolfram.com/Cone.html} 找到")

Ce(ecx.lhs,ecx.rhs)
Ce(ecy.lhs,ecy.rhs)
Ce(ecz.lhs,ecz.rhs)

Ce(base, nbase)
Ce(height,nheight)
Ce(ecdelta.lhs,ecdelta.rhs)
Ce(ec1.lhs,ec1.rhs)
Ce(ec2.lhs,ec2.rhs)

Ce(phi,Matrix([cphi[0],cphi[1],vdots,cphi[res-1]]))
Ce(x,Matrix([cx[0],cx[1],vdots,cx[res-1]]))
Ce(y,Matrix([cy[0],cy[1],vdots,cy[res-1]]))

Ce(z,z1)

At("\\section{Surface Plot of a Cone 圆锥体的曲面图}")

At("The mathematical expression for surface plot is expressed as follows.")
At("曲面图的数学表达式表示如下。")


Ce(z,fF(x,y),c = "\\quad where x and y are independent variables \par 其中 x 和 y 是自变量")
Ce(x,fF(z,y),c = "\\quad where z and y are independent variables \par 其中 z 和 y 是自变量")
Ce(y,fF(x,z),c = "\\quad where x and z are independent variables \par 其中 x 和 z 是自变量" )


At("The surface plots of a cone in Figure 1.1 were generated by cone01.py codes. \
The dependent variable is z and the independent variables are x and y. The equations of \
both plots are based on polar coordinate equations. The algorithms however are different.")

At("图 1.1 中圆锥体的曲面图是由 cone01.py 代码生成的。 因变量是 z，自变量是 x 和 y。 \
两个图的方程均基于极坐标方程。 然而，算法是不同的。")


At("The surface plots requires a combination of two independent variables. \
The combination of two independent variables is produced by meshgrid function \
that has shape of a tuple of two values, that is for 100 values, the shape=(100,100). \
The independent variable must be expressed in terms of independent meshgrid \
independent variables. Hence, it must have the same shape of 2.")

At("曲面图需要两个自变量的组合。 两个自变量的组合由 meshgrid 函数生成，\
该函数具有两个值的元组形状，即 100 个值，形状=(100,100)。 自变量必须以独立网格自变量的形式表示。 \
因此，它必须具有与 2 相同的形状。")




from cone02 import *

At("\\section{Intersection of a Cone and of a Plane 圆锥体与平面的交点}")

At("The equation of a plane is expressed as follows.")

At("平面的方程表达如下。")


Ce(A*x+B*y+C*z+K,0)

Ce(Eq(z,fF(x,y)),sz)


At("The equation above can create the plane as shown in Figure 3.1")
At("上面的方程可以创建如图3.1所示的平面")



Af("Data/fgr02.png",caption="A plane overlapping with cone. 与圆锥重叠的平面。",height=.35)


At("The intersection of a cone and a plane defines a locus of points that \
can be expressed as equations of a line.")

At("圆锥体和平面的交点定义了可以表示为直线方程的点轨迹。")



At("The equations of a line consist of two equation of intersecting surfaces \
where two of the axes are dependent variable and the third axis is independent \
variable. The two equations for the surfaces can be solved for two variables and \
the third variable is the arbitrary variable or independent varialbe.")

At("直线方程由两个相交曲面方程组成，其中两个轴是因变量，第三个轴是自变量。 \
表面的两个方程可以针对两个变量求解，第三个变量是任意变量或自变量。")

from cone03 import *

At("\\section{Conic Sections 圆锥截面}")

At("The Figure 3 illustrate the mirrored cones that define conic section.")

At("图 3 说明了定义圆锥截面的镜面圆锥体。")

Af("Data/fgr03.png",caption="Cones section that defined a circle. 定义圆的圆锥截面。",height=.7)


At("The disk plane intersecting with a cone generates a circle of locus of points.")
At("与圆锥体相交的圆盘平面生成点轨迹圆。")


At("The disk could be tilted and the locus of points forms an elipse.")
At("圆盘可以倾斜，点的轨迹形成椭圆。")

Af("Data/fgr04.png",caption="Conic section cut by disk plane at an angle genrated \
an elipse an eliptical locus of points. 圆盘平面以一定角度切割的圆锥截面生成椭圆和椭圆点轨迹。",height=.3)

At("When the tilt is in parallel with the slope of the side of the cone, the \
   locus of points form a parabola.")

At("当倾斜与圆锥侧面的斜率平行时，点的轨迹形成抛物线。")


Af("Data/fgr05.png",caption="A Conic section that generated a parabola. \
生成抛物线的圆锥曲线。",height=.7)

At("When the disk plane is in parallel with the vertical axis of the cone, \
   the locus of points forms a hyperbola. Note the intersection cut across \
   both the upper and lower cones.")

At("当圆盘平面与圆锥的垂直轴平行时，点的轨迹形成双曲线。 注意穿过上锥体和下锥体的交点。")


Af("Data/fgr06.png",caption="A Conic section that generated a hyperbola. \
生成双曲线的圆锥曲线。 ",height=.7)


At("\\nocite{2}")
At("\\nocite{3}")
At("\\nocite{7}")
At("\\nocite{8}")
At("\\nocite{9}")
At("\\nocite{11}")
At("\\nocite{13}")
At("\\nocite{15}")
At("\\nocite{202}")
At("\\nocite{203}")


#At("\\bibliographystyle{plain} \n \\bibliography{ccoLib/ccoBook,ccoLib/ccoArticle}")
At("\\bibliographystyle{plain} \n \\bibliography{ccoLib/ccobib}")


At("\\end{CJK*}")

Pb(Filename="eNotes01ECT.tex")
