# -*- coding: utf-8 -*-
"""
Filename: eNotes01.py
Created on Fri Feb  9 20:41:48 2024

@author: Celso Co
"""

from ccoLib.ccoPlot  import *
from ccoLib.ccoLatex import *  #This is the library for Python-Tex coding.
from Data.variables import *

title="eNotes: The Conic Section"
authors="CBCO"
date=""

Preamble="\\documentclass[10pt,a4paper,leqno]{article}\n\
\\usepackage{CJKutf8}\n\
\\usepackage[utf8]{inputenc}\n\
\\usepackage[T1]{fontenc}\n\
\\usepackage{amsmath,esint}\n\
\\usepackage{amsfonts}\n\
\\usepackage{amssymb}\n\
\\usepackage{xcolor}\n\
\\usepackage{mathrsfs}\n\
\\usepackage{makeidx}\n\
\\usepackage{graphicx}\n\
\\usepackage{float}\n\
\\usepackage{gensymb}\n\
\\usepackage{textcomp}\n\
\\usepackage{longtable}\n\
\\usepackage{ifpdf}\n\
\\usepackage{tikz}                            \n\
\\usetikzlibrary{shapes,arrows}               \n\
%\\usepackage{tgothic}\n\
\\ifpdf\n\
\\usepackage[breaklinks,hidelinks]{hyperref}\n\
\\else \n\
\\usepackage{url}\n\
\\fi\n\
\\newcommand*\VF[1]{\mathbf{#1}}\n\
\\newcommand*\dif{\mathop{}\!\mathrm{d}}\n\
\\author{"+authors+"}\n\
\\title{"+title+"}\n\
\\date{"+date+"}\n\
\\begin{document}\n\
\\maketitle\n\n"


PyArt=PyArticle(Headers=Preamble)
          
             
#Shortcut Handlers 

At=PyArt.Append_Text            #Append text variable
Ae=PyArt.Append_Expression      #Append expression
Ce=PyArt.Append_Equation        #Create equation
Pb=PyArt.Build                  #Build Latex File
Af=PyArt.Append_Figure          #Append figure
Ad=PyArt.Append_Var_Dictionary  #Append Variable Dictionary
Ml=PyArt.Math_Latex             #Convertion to Math format latex    
eQ=PyArt.eQ                     #Equation List
vD=PyArt.vD                     #Variable List
   


#Multiple Choices
"""
At("\\newcommand\\CWht[1][2.5]{\\tikz[baseline=-#1]{\\draw[thick](0,0) \
    circle[radius=1.5mm];}}")
#CBlk is circle with black fill
At("\\newcommand\\CBlk[1][2.5]{\\tikz[baseline=-#1]{\\draw[thick,\
    fill=black!](0,0) circle[radius=1.5mm];}}")
"""

#Numbering equation within section
At("\\numberwithin{equation}{section} % This line resets equation numbering \
when starting a new section. \n\
\\renewcommand{\\theequation}{\\thesection.\\arabic{equation}}  \n\
%\\renewcommand{\\theequation}{Eq. \\thesection.\\arabic{equation}} % This line ads Eq.")

At("\\numberwithin{figure}{section}\n\
% \\renewcommand{\theequation}{Eq. \thesection.\arabic{equation}}")   

At("\\begin{CJK*}{UTF8}{gbsn}")

from cone01 import *

At("\\section{Introduction }")

At("A conic section is an intersection of a cone with a plnae.")


At("In Figure 1.1, the cones were plotted with two different methods.")



Af("Data/fgr01.png",caption="(a) Cone = f(x,y,z) plot (b) Cone = f(rho,phi,z) ",
   height=.25)

At("Open Cone01.py. Study the codes and run the file.")


At("The equation of cone can be found at \\url{https://mathworld.wolfram.com/Cone.html} ")

Ce(ecx.lhs,ecx.rhs)
Ce(ecy.lhs,ecy.rhs)
Ce(ecz.lhs,ecz.rhs)

Ce(base, nbase)
Ce(height,nheight)
Ce(ecdelta.lhs,ecdelta.rhs)
Ce(ec1.lhs,ec1.rhs)
Ce(ec2.lhs,ec2.rhs)

Ce(phi,Matrix([cphi[0],cphi[1],vdots,cphi[res-1]]))
Ce(x,Matrix([cx[0],cx[1],vdots,cx[res-1]]))
Ce(y,Matrix([cy[0],cy[1],vdots,cy[res-1]]))

Ce(z,z1)

At("\\section{Surface Plot of a Cone }")

At("The mathematical expression for surface plot is expressed as follows.")


Ce(z,fF(x,y),c = "\\quad where x and y are independent variables \par 其中 x 和 y 是自变量")
Ce(x,fF(z,y),c = "\\quad where z and y are independent variables \par 其中 z 和 y 是自变量")
Ce(y,fF(x,z),c = "\\quad where x and z are independent variables \par 其中 x 和 z 是自变量" )


At("The surface plots of a cone in Figure 1.1 were generated by cone01.py codes. \
The dependent variable is z and the independent variables are x and y. The equations of \
both plots are based on polar coordinate equations. The algorithms however are different.")



At("The surface plots requires a combination of two independent variables. \
The combination of two independent variables is produced by meshgrid function \
that has shape of a tuple of two values, that is for 100 values, the shape=(100,100). \
The independent variable must be expressed in terms of independent meshgrid \
independent variables. Hence, it must have the same shape of 2.")





from cone02 import *

At("\\section{Intersection of a Cone and of a Plane }")

At("The equation of a plane is expressed as follows.")



Ce(A*x+B*y+C*z+K,0)

Ce(Eq(z,fF(x,y)),sz)


At("The equation above can create the plane as shown in Figure 3.1")



Af("Data/fgr02.png",caption="A plane overlapping with cone.",height=.35)


At("The intersection of a cone and a plane defines a locus of points that \
can be expressed as equations of a line.")




At("The equations of a line consist of two equation of intersecting surfaces \
where two of the axes are dependent variable and the third axis is independent \
variable. The two equations for the surfaces can be solved for two variables and \
the third variable is the arbitrary variable or independent varialbe.")


from cone03 import *

At("\\section{Conic Sections }")

At("The Figure 3 illustrate the mirrored cones that define conic section.")


Af("Data/fgr03.png",caption="Cones section that defined a circle. ",height=.7)


At("The disk plane intersecting with a cone generates a locus of points of \
    circle.")

At("The disk could be tilted and the locus of points forms an elipse.")

Af("Data/fgr04.png",caption="Conic section cut by disk plane at an angle genrated \
an elipse an eliptical locus of points.",height=.3)

At("When the tilt is in parallel with the slope of the side of the cone, the \
   locus of points form a parabola.")

Af("Data/fgr05.png",caption="A Conic section that generated a parabola. ",height=.7)


At("When the disk plane is in parallel with the vertical axis of the cone, \
   the locus of points forms a hyperbola. Note the intersection cut across \
   both the upper and lower cones.")

Af("Data/fgr06.png",caption="A Conic section that generated a hyperbola. ",height=.7)


At("\\nocite{2}")
At("\\nocite{3}")
At("\\nocite{7}")
At("\\nocite{8}")
At("\\nocite{9}")
At("\\nocite{11}")
At("\\nocite{13}")
At("\\nocite{15}")
At("\\nocite{202}")
At("\\nocite{203}")





#At("\\bibliographystyle{plain} \n \\bibliography{ccoLib/ccoBook,ccoLib/ccoArticle}")
At("\\bibliographystyle{plain} \n \\bibliography{ccoLib/ccobib}")


At("\\end{CJK*}")

Pb(Filename="eNotes01.tex")
